# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s15ftgb196-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir H:/Desktop/Shape_recognition/Shape_recognition.cache/wt [current_project]
set_property parent.project_path H:/Desktop/Shape_recognition/Shape_recognition.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths h:/Desktop/Shape_recognition/Shape_recognition_IP [current_project]
update_ip_catalog
set_property ip_output_repo h:/Desktop/Shape_recognition/Shape_recognition.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/imports/new/CLK_Division.v
  H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/imports/new/Driver_Bayer_To_RGB.v
  H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/imports/new/Driver_Csi_To_Dvp.v
  H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/imports/new/Driver_IIC.v
  H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/new/Driver_MIPI1.v
  H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/imports/new/Driver_UART.v
  H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/imports/new/OV5647_Init.v
  H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/new/RGB_To_Gray.v
  H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/new/Recognize_Top.v
  H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/new/Shape_Judge.v
  H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/new/Shape_send.v
  H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/new/Threshold_Judge.v
  H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/new/Shape_recognition.v
}
read_ip -quiet H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
set_property used_in_implementation false [get_files -all h:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all h:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc]

read_ip -quiet H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/csi2_d_phy_rx_0/csi2_d_phy_rx_0.xci
set_property used_in_implementation false [get_files -all h:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/csi2_d_phy_rx_0/hdl/csi2_d_phy_rx.xdc]

read_ip -quiet H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/csi_to_axis_0/csi_to_axis_0.xci
set_property used_in_implementation false [get_files -all h:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/csi_to_axis_0/hdl/csi_to_axis.xdc]

read_ip -quiet H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all h:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all h:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all h:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all h:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all h:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all h:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

read_ip -quiet H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all h:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet H:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all h:/Desktop/Shape_recognition/Shape_recognition.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc H:/Desktop/Shape_recognition/Shape_recognition.srcs/constrs_1/imports/new/system.xdc
set_property used_in_implementation false [get_files H:/Desktop/Shape_recognition/Shape_recognition.srcs/constrs_1/imports/new/system.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Shape_recognition -part xc7s15ftgb196-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Shape_recognition.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Shape_recognition_utilization_synth.rpt -pb Shape_recognition_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
